<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2020-06-24T14:03:59-04:00" hostname="https://syngentacanada--full.my.salesforce.com" tests="4" failures="1"  errors="0"  time="20.27">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="4"/>
            <property name="passing" value="3"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="75%"/>
            <property name="failRate" value="25%"/>
            <property name="testStartTime" value="Jun 24, 2020 2:03 PM"/>
            <property name="testExecutionTime" value="20.27 s"/>
            <property name="testTotalTime" value="20.27 s"/>
            <property name="commandTime" value="42.44 s"/>
            <property name="hostname" value="https://syngentacanada--full.my.salesforce.com"/>
            <property name="orgId" value="00D6300000024c2EAA"/>
            <property name="username" value="aakash.sidana@syngenta.com.full"/>
            <property name="testRunId" value="7076300001VrLfO"/>
            <property name="userId" value="0053m00000AlyrWAAR"/>
            <property name="testRunCoverage" value="81%"/>
            <property name="orgWideCoverage" value="74%"/>
        </properties>
        <testcase name="testCallout" classname="CalloutClassTest" time="3.1">
            <failure message="System.FinalException: Testing has not started"><![CDATA[Class.System.Test.stopTest: line 19, column 1
Class.CalloutClassTest.testCallout: line 40, column 1]]></failure>
        </testcase>
        <testcase name="runTest" classname="Contact_TriggerTest" time="6.71">
        </testcase>
        <testcase name="runTest" classname="Contact_TriggerTest2" time="4.09">
        </testcase>
        <testcase name="runTest" classname="Contact_Trigger_Primary_Contact_Test" time="6.37">
        </testcase>
    </testsuite>
</testsuites>
