<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2020-06-01T11:30:13-04:00" hostname="https://syngentacanada--full.my.salesforce.com" tests="1" failures="1"  errors="0"  time="3.83">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="1"/>
            <property name="passing" value="0"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="0%"/>
            <property name="failRate" value="100%"/>
            <property name="testStartTime" value="Jun 1, 2020 11:30 AM"/>
            <property name="testExecutionTime" value="3.83 s"/>
            <property name="testTotalTime" value="3.83 s"/>
            <property name="commandTime" value="97.92 s"/>
            <property name="hostname" value="https://syngentacanada--full.my.salesforce.com"/>
            <property name="orgId" value="00D2g0000008aPPEAY"/>
            <property name="username" value="aakash.sidana@syngenta.com.full"/>
            <property name="testRunId" value="7072g00000GA4hK"/>
            <property name="userId" value="0053m00000AlyrWAAR"/>
            <property name="testRunCoverage" value="78%"/>
            <property name="orgWideCoverage" value="58%"/>
        </properties>
        <testcase name="runTest" classname="Contact_TriggerTest" time="3.83">
            <failure message="System.TypeException: DML operation INSERT not allowed on Account"><![CDATA[Class.Contact_TriggerTest.runTest: line 37, column 1]]></failure>
        </testcase>
    </testsuite>
</testsuites>
