<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2020-06-24T13:17:10-04:00" hostname="https://syngentacanada--full.my.salesforce.com" tests="4" failures="1"  errors="0"  time="24.25">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="4"/>
            <property name="passing" value="3"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="75%"/>
            <property name="failRate" value="25%"/>
            <property name="testStartTime" value="Jun 24, 2020 1:17 PM"/>
            <property name="testExecutionTime" value="24.25 s"/>
            <property name="testTotalTime" value="24.25 s"/>
            <property name="commandTime" value="50.38 s"/>
            <property name="hostname" value="https://syngentacanada--full.my.salesforce.com"/>
            <property name="orgId" value="00D6300000024c2EAA"/>
            <property name="username" value="aakash.sidana@syngenta.com.full"/>
            <property name="testRunId" value="7076300001VrJAg"/>
            <property name="userId" value="0053m00000AlyrWAAR"/>
            <property name="testRunCoverage" value="81%"/>
            <property name="orgWideCoverage" value="74%"/>
        </properties>
        <testcase name="testCallout" classname="CalloutClassTest" time="0.03">
            <failure message="System.AssertException: Assertion Failed"><![CDATA[Class.CalloutClassTest.testCallout: line 19, column 1]]></failure>
        </testcase>
        <testcase name="runTest" classname="Contact_TriggerTest" time="13.04">
        </testcase>
        <testcase name="runTest" classname="Contact_TriggerTest2" time="5.51">
        </testcase>
        <testcase name="runTest" classname="Contact_Trigger_Primary_Contact_Test" time="5.66">
        </testcase>
    </testsuite>
</testsuites>
