<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2020-06-05T10:23:45-04:00" hostname="https://syngentacanada--full.my.salesforce.com" tests="3" failures="1"  errors="0"  time="21.7">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="3"/>
            <property name="passing" value="2"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="67%"/>
            <property name="failRate" value="33%"/>
            <property name="testStartTime" value="Jun 5, 2020 10:23 AM"/>
            <property name="testExecutionTime" value="21.7 s"/>
            <property name="testTotalTime" value="21.7 s"/>
            <property name="commandTime" value="17.46 s"/>
            <property name="hostname" value="https://syngentacanada--full.my.salesforce.com"/>
            <property name="orgId" value="00D2g0000008aPPEAY"/>
            <property name="username" value="aakash.sidana@syngenta.com.full"/>
            <property name="testRunId" value="7072g00000GfkXH"/>
            <property name="userId" value="0053m00000AlyrWAAR"/>
            <property name="testRunCoverage" value="77%"/>
            <property name="orgWideCoverage" value="64%"/>
        </properties>
        <testcase name="runTest" classname="Contact_TriggerTest" time="5.54">
            <failure message="System.AssertException: Assertion Failed: Expected: true, Actual: false"><![CDATA[Class.Contact_TriggerTest.runTest: line 59, column 1]]></failure>
        </testcase>
        <testcase name="runTest" classname="Contact_TriggerTest2" time="7.41">
        </testcase>
        <testcase name="runTest" classname="Contact_Trigger_Primary_Contact_Test" time="8.75">
        </testcase>
    </testsuite>
</testsuites>
